Repository KarmaKamikaze/STEP, pull requests merged in 2022-04, with the labels that each got.

#3 Feature/ast printer
  Example programs/assman.step
  Example programs/cm_to_inch_converter.step
  Example programs/sarmimath.step
  STEP.grammar
  STEP/AstPrinter.cs
  STEP/Program.cs
  STEP/STEP.csproj
  STEP/analysis.cs
  STEP/lexer.cs
  STEP/parser.cs
  STEP/prods.cs
  STEP/tokens.cs
Labels: enhancement

#4 Feature/pretty printer
  STEP.grammar
  STEP/AstPrinter.cs
  STEP/Program.cs
  STEP/analysis.cs
  STEP/parser.cs
  STEP/prods.cs
Labels: enhancement

#5 Grammar changes
  Example programs/arraytests.step
  Example programs/cm_to_inch_converter.step
  Example programs/contbreak.STEP
  STEP.grammar
  STEP/analysis.cs
  STEP/lexer.cs
  STEP/parser.cs
  STEP/prods.cs
Labels: enhancement

#7 Feature/antlr
  Example programs/cm_to_inch_converter.step
  STEP/AstPrinter.cs
  STEP/PrettyPrinter.cs
  STEP/Program.cs
  STEP/STEP.csproj
  STEP/STEP.g4
  STEP/STEP.interp
  STEP/STEP.tokens
  STEP/STEPBaseListener.cs
  STEP/STEPBaseVisitor.cs
  STEP/STEPLexer.cs
  STEP/STEPLexer.interp
  STEP/STEPLexer.tokens
  STEP/STEPListener.cs
  STEP/STEPParser.cs
  STEP/STEPVisitor.cs
  STEP/analysis.cs
  STEP/lexer.cs
  STEP/nodes.cs
  STEP/parser.cs
  STEP/prods.cs
  STEP/tokens.cs
Labels: enhancement

#8 Feature/if statement grammar fix
  Example programs/continue_break_tests.step
  Example programs/elseif_chaining.step
  STEP/ANTLR gens/STEP.g4
  STEP/ANTLR gens/STEP.interp
  STEP/ANTLR gens/STEP.tokens
  STEP/ANTLR gens/STEPBaseListener.cs
  STEP/ANTLR gens/STEPBaseVisitor.cs
  STEP/ANTLR gens/STEPLexer.cs
  STEP/ANTLR gens/STEPLexer.interp
  STEP/ANTLR gens/STEPLexer.tokens
  STEP/ANTLR gens/STEPListener.cs
  STEP/ANTLR gens/STEPParser.cs
  STEP/ANTLR gens/STEPVisitor.cs
  STEP/AST/AstBuilderVisitor.cs
  STEP/AST/AstPrintVisitor.cs
  STEP/AST/Nodes/AndNode.cs
  STEP/AST/Nodes/ArrDclNode.cs
  STEP/AST/Nodes/ArrLiteralNode.cs
  STEP/AST/Nodes/ArrayAccessNode.cs
  STEP/AST/Nodes/AssNode.cs
  STEP/AST/Nodes/AstNodeType.cs
  STEP/AST/Nodes/BoolNode.cs
  STEP/AST/Nodes/BreakNode.cs
  STEP/AST/Nodes/ContNode.cs
  STEP/AST/Nodes/DivNode.cs
  STEP/AST/Nodes/ElseIfNode.cs
  STEP/AST/Nodes/EqNode.cs
  STEP/AST/Nodes/ForNode.cs
  STEP/AST/Nodes/FuncDefNode.cs
  STEP/AST/Nodes/FuncExprNode.cs
  STEP/AST/Nodes/FuncStmtNode.cs
  STEP/AST/Nodes/FuncsNode.cs
  STEP/AST/Nodes/GThanEqNode.cs
  STEP/AST/Nodes/GThanNode.cs
  STEP/AST/Nodes/IdNode.cs
  STEP/AST/Nodes/IfNode.cs
  STEP/AST/Nodes/LThanEqNode.cs
  STEP/AST/Nodes/LThanNode.cs
  STEP/AST/Nodes/LoopNode.cs
  STEP/AST/Nodes/MinusNode.cs
  STEP/AST/Nodes/MultNode.cs
  STEP/AST/Nodes/NegNode.cs
  STEP/AST/Nodes/NeqNode.cs
  STEP/AST/Nodes/NodeFactory.cs
  STEP/AST/Nodes/NumberNode.cs
  STEP/AST/Nodes/OrNode.cs
  STEP/AST/Nodes/ParenNode.cs
  STEP/AST/Nodes/PlusNode.cs
  STEP/AST/Nodes/PowNode.cs
  STEP/AST/Nodes/ProgNode.cs
  STEP/AST/Nodes/RetNode.cs
  STEP/AST/Nodes/SetupNode.cs
  STEP/AST/Nodes/StringNode.cs
  STEP/AST/Nodes/UMinusNode.cs
  STEP/AST/Nodes/VarDclNode.cs
  STEP/AST/Nodes/VarsNode.cs
  STEP/AST/Nodes/WhileNode.cs
  STEP/IVisitor.cs
  STEP/TypeVisitor.cs
  StepTests/ASTVisitorTests.cs
Labels: bug

#11 CodeGen outputs to file and links to arduino compiler
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  STEP/PrettyPrinter.cs
  STEP/Program.cs
Labels: enhancement

#16 Type switch for code gen
  STEP/CodeGeneration/CodeGenerationVisitor.cs
Labels: enhancement

#12 Feature/codegen str concat
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  StepTests/CodeGenerationVisitorTests.cs
Labels: enhancement

#18 Feature/codegen elseif and fundcl
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  StepTests/CodeGenerationVisitorTests.cs
Labels: bug, enhancement

#19 Feature/pin code gen
  Example programs/cm_to_inch_converter.step
  Example programs/testboi.step
  STEP/AST/AstBuilderVisitor.cs
  STEP/AST/AstPrintVisitor.cs
  STEP/AST/Nodes/AstNodeType.cs
  STEP/AST/Nodes/NodeFactory.cs
  STEP/AST/Nodes/PinDclNode.cs
  STEP/AST/Nodes/VarsNode.cs
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  STEP/IVisitor.cs
  STEP/PinCodeVisitor.cs
  STEP/PinType.cs
  STEP/TypeVisitor.cs
  StepTests/TypeCheckerTests.cs
Labels: enhancement

#22 Fixed error in PinDclNode code generator. Corrected by visiting right child instead of left.
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  StepTests/CodeGenerationVisitorTests.cs
Labels: bug

#25 Feature/integrationtest
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  StepTests/IntegrationTestPrograms/int2Expected.ino
  StepTests/IntegrationTestPrograms/int2Source.step
  StepTests/IntegrationTestPrograms/printArrayExpected.ino
  StepTests/IntegrationTestPrograms/printArraySource.step
  StepTests/IntegrationTests.cs
Labels: enhancement

#28 I hope this will save a few retinas from severe inflamation
  Example programs/assman.step
  Example programs/contbreak.STEP
  Example programs/sarmimath.step
  Example programs/sarmiprint.STEP
  Example programs/testboi.step
Labels: enhancement

#29 Declaring a pin will now define a constant variable name in generated…
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  STEP/PinCodeVisitor.cs
  StepTests/CodeGenerationVisitorTests.cs
Labels: enhancement

#32 Ensured that setup() and loop() are always generated
  STEP/AST/StandardEnvironment.cs
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  StepTests/StandardEnvironmentTests.cs
Labels: enhancement

#33 Feature/arduino uploader
  .gitignore
  Example programs/testboi.step
  STEP/ArduinoCompiler.cs
  STEP/CodeGeneration/CodeGenerationVisitor.cs
  STEP/Program.cs
  STEP/STEP.csproj
  STEP/avr-destination/bin/avr-addr2line.exe
  STEP/avr-destination/bin/avr-ar.exe
  STEP/avr-destination/bin/avr-as.exe
  STEP/avr-destination/bin/avr-c++.exe
  STEP/avr-destination/bin/avr-c++filt.exe
  STEP/avr-destination/bin/avr-cpp.exe
  STEP/avr-destination/bin/avr-elfedit.exe
  STEP/avr-destination/bin/avr-g++.exe
  STEP/avr-destination/bin/avr-gcc-5.4.0.exe
  STEP/avr-destination/bin/avr-gcc-ar.exe
  STEP/avr-destination/bin/avr-gcc-nm.exe
  STEP/avr-destination/bin/avr-gcc-ranlib.exe
  STEP/avr-destination/bin/avr-gcc.exe
  STEP/avr-destination/bin/avr-gcov-tool.exe
  STEP/avr-destination/bin/avr-gcov.exe
  STEP/avr-destination/bin/avr-gdb-py.exe
  STEP/avr-destination/bin/avr-gdb.exe
  STEP/avr-destination/bin/avr-gprof.exe
  STEP/avr-destination/bin/avr-ld.bfd.exe
  STEP/avr-destination/bin/avr-ld.exe
  STEP/avr-destination/bin/avr-man
  STEP/avr-destination/bin/avr-nm.exe
  STEP/avr-destination/bin/avr-objcopy.exe
  STEP/avr-destination/bin/avr-objdump.exe
  STEP/avr-destination/bin/avr-ranlib.exe
  STEP/avr-destination/bin/avr-readelf.exe
  STEP/avr-destination/bin/avr-size.exe
  STEP/avr-destination/bin/avr-strings.exe
  STEP/avr-destination/bin/avr-strip.exe
Labels: enhancement
